### ISSUE TITLE
Activity classes missing in repository

### ISSUE THREAD

**Issue by larsblumberg** [johncarl81/androiddraw#1]
In order to run this Android app out of the box, having the activity classes as well would be helpful. Thanks for your work!

**Comment by johncarl81** [comment]
The Android Activity classes are generated during the build by [Transfuse](androidtranfuse.org).  Just run `mvn clean install` to trigger the tool.

**Comment by larsblumberg** [comment]
Indeed, I just found this out :) Did you already create a comparison Matrix for Transfusion, Android Annotations and Dagger as you had in mind in http://stackoverflow.com/questions/17375523/transfuse-vs-androidannotations#17644501 ?

**Comment by johncarl81** [comment]
I haven't yet.. although quite a few people have asked for it.  I'd probably want to get representatives from each project to collaborate on the matrix so it is fair.  I would hope a good comparison would highlight really how different Transfuse, AA and Dagger really are (maybe include Roboguice, Roboject, GreenInject, and others)

If you're interested, there is a performance comparison project here that highlights the differences between Dagger, Roboguice and Transfuse: https://github.com/patrickbaumann/daggervsroboguice
